### PR TITLE
Fatal error fixes

### PR DESCRIPTION
**Pull request by tomzaragoza**
mention-ghost-theme-errors

### CODE REVIEW

**Comment by shtefcs** [comment]
Hey @tomzaragoza , did you manage to fix it ? I guess it should be updated, since its bit old theme.

**Comment by tomzaragoza** [comment]
Hey @shtefcs, yup I did. I'll re-open the PR.

**Comment by shtefcs** [comment]
Great @tomzaragoza , lets wait for @jelenajjo and she will merge. She is coming soon to my place, we gonna celeb New Year.

All best to you to friend.

**Comment by tomzaragoza** [comment]
Sounds good. Happy New Year to you both, @shtefcs & @jelenajjo !

**Comment by jelenajjo** [comment]
Thanks @tomzaragoza for the pull request and Happy New year to you too! :)

**Pull request merged**
